### ISSUE TITLE
设置好S3存储后还是默认保存到本地以及#96的问题又出现了

### ISSUE THREAD

**Issue by ChanLicher** [vastsa/FileCodeBox#178]
①如题，我的环境是docker
![PixPin_2024-06-18_00-05-44](https://github.com/vastsa/FileCodeBox/assets/55681496/16151559-0ce4-4a25-be6c-807e7a464781)
我的设置应该没错吧，后台日志也没任何报错信息。

②还有#96的问题又出现了，我按照日志修改后可以用了，但是就像上面说的，只能本地存储。日志如下：
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/apps/base/views.py", line 41, in share_file
    if file.size > settings.uploadSize:
TypeError: '>' not supported between instances of 'int' and 'str'
```

麻烦作者修复一下~

**Comment by vastsa** [comment]
好滴，等我排查一下

**Comment by vastsa** [comment]
你这个regionname没问题吧

**Comment by vastsa** [comment]
什么时候更新的docker

**Comment by vastsa** [comment]
以及修复了，改成单例模式

**Comment by ChanLicher** [comment]
非常感谢！现在可以用了，地区确实不能用中文，我直接留空，signature改为v4就可以了
