### ISSUE TITLE
[Bug]Upload failed by use S3

### ISSUE THREAD

**Issue by carolcoral** [vastsa/FileCodeBox#210]
**Describe the bug**
Can not upload file by use minio(S3) as storage.

**To Reproduce**
1. First of all, i set minio(S3) as my storage
2. then i tried to send a file.
3. It mentioned me `upload failed`
4. But, i had watched bucket in my minio server, find the `file`

**Expected behavior**

**Screenshots**
<img width="1386" alt="image" src="https://github.com/user-attachments/assets/8bb89775-695c-4d78-9ff7-a77ea3c970b1">
<img width="997" alt="image" src="https://github.com/user-attachments/assets/41fb4129-8cc8-4a75-8c04-218e6cc77865">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 15.0.1

**Additional context**

Build server by use docker compose.

**Log**

```yaml
1Panel-filecodebox-JntI  | INFO:     172.18.0.1:49594 - "GET /admin/local/lists HTTP/1.1" 500 Internal Server Error
1Panel-filecodebox-JntI  | ERROR:    Exception in ASGI application
1Panel-filecodebox-JntI  | Traceback (most recent call last):
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
1Panel-filecodebox-JntI  |     result = await app(  # type: ignore[func-returns-value]
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
1Panel-filecodebox-JntI  |     return await self.app(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
1Panel-filecodebox-JntI  |     await super().__call__(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
1Panel-filecodebox-JntI  |     await self.middleware_stack(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
1Panel-filecodebox-JntI  |     raise exc
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
1Panel-filecodebox-JntI  |     await self.app(scope, receive, _send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
1Panel-filecodebox-JntI  |     await self.app(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
1Panel-filecodebox-JntI  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
1Panel-filecodebox-JntI  |     raise exc
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
1Panel-filecodebox-JntI  |     await app(scope, receive, sender)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 715, in __call__
1Panel-filecodebox-JntI  |     await self.middleware_stack(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 735, in app
1Panel-filecodebox-JntI  |     await route.handle(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
1Panel-filecodebox-JntI  |     await self.app(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
1Panel-filecodebox-JntI  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
1Panel-filecodebox-JntI  |     raise exc
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
1Panel-filecodebox-JntI  |     await app(scope, receive, sender)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
1Panel-filecodebox-JntI  |     response = await f(request)
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 301, in app
1Panel-filecodebox-JntI  |     raw_response = await run_endpoint_function(
1Panel-filecodebox-JntI  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
1Panel-filecodebox-JntI  |     return await dependant.call(**values)
1Panel-filecodebox-JntI  |   File "/app/apps/admin/views.py", line 79, in get_local_lists
1Panel-filecodebox-JntI  |     files = await local_file_service.list_files()
1Panel-filecodebox-JntI  |   File "/app/apps/admin/services.py", line 93, in list_files
1Panel-filecodebox-JntI  |     for file in os.listdir(data_root / 'local'):
1Panel-filecodebox-JntI  | FileNotFoundError: [Errno 2] No such file or directory: '/app/data/local'
1Panel-filecodebox-JntI  | INFO:     172.18.0.1:35436 - "GET /assets/SettingView-DgrpsovJ.css HTTP/1.1" 200 OK
1Panel-filecodebox-JntI  | INFO:     172.18.0.1:35440 - "GET /assets/SettingView-B73Vn17x.js HTTP/1.1" 200 OK
1Panel-filecodebox-JntI  | INFO:     172.18.0.1:43358 - "GET /admin/config/get HTTP/1.1" 200 OK

```

**Comment by vastsa** [comment]
get

**Comment by vastsa** [comment]
After updating the storage method, please restart Docker or the service
