### ISSUE TITLE
V2.1无法使用cloudflare的R2存储

### ISSUE THREAD

**Issue by Frankcsc** [vastsa/FileCodeBox#217]
Docker部署的最新版本，lanol/filecodebox:beta

![图片](https://github.com/user-attachments/assets/de0c292b-3109-46f4-95b1-1e0360f5a267)

![图片](https://github.com/user-attachments/assets/3cb4cace-4cd0-4a53-8119-b0cd64932e7d)

日志：

```
2024-11-24T09:02:56.989033660Z INFO:     192.168.112.1:54308 - "GET /admin/config/get HTTP/1.1" 200 OK
2024-11-24T09:02:57.087478584Z INFO:     192.168.112.1:54312 - "GET /admin/dashboard HTTP/1.1" 200 OK
2024-11-24T09:03:35.193187925Z INFO:     192.168.112.1:50550 - "PATCH /admin/config/update HTTP/1.1" 200 OK
2024-11-24T09:03:42.118935733Z INFO:     192.168.112.1:34832 - "GET / HTTP/1.1" 200 OK
2024-11-24T09:03:43.005125432Z INFO:     192.168.112.1:34838 - "POST / HTTP/1.1" 200 OK
2024-11-24T09:03:54.315729550Z INFO:     192.168.112.1:50930 - "POST /share/file/ HTTP/1.1" 500 Internal Server Error
2024-11-24T09:03:54.370220774Z ERROR:    Exception in ASGI application
2024-11-24T09:03:54.370252379Z Traceback (most recent call last):
2024-11-24T09:03:54.370277699Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-11-24T09:03:54.370284519Z     result = await app(  # type: ignore[func-returns-value]
2024-11-24T09:03:54.370287830Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-11-24T09:03:54.370291787Z     return await self.app(scope, receive, send)
2024-11-24T09:03:54.370295069Z   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
2024-11-24T09:03:54.370298668Z     await super().__call__(scope, receive, send)
2024-11-24T09:03:54.370302147Z   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
2024-11-24T09:03:54.370305826Z     await self.middleware_stack(scope, receive, send)
2024-11-24T09:03:54.370308770Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
2024-11-24T09:03:54.370311860Z     raise exc
2024-11-24T09:03:54.370315135Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
2024-11-24T09:03:54.370319044Z     await self.app(scope, receive, _send)
2024-11-24T09:03:54.370322581Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 93, in __call__
2024-11-24T09:03:54.370326037Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-11-24T09:03:54.370328785Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 144, in simple_response
2024-11-24T09:03:54.370331426Z     await self.app(scope, receive, send)
2024-11-24T09:03:54.370333803Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-11-24T09:03:54.370336333Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-11-24T09:03:54.370338852Z   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-11-24T09:03:54.370341372Z     raise exc
2024-11-24T09:03:54.370343665Z   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-11-24T09:03:54.370346190Z     await app(scope, receive, sender)
2024-11-24T09:03:54.370348545Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 715, in __call__
2024-11-24T09:03:54.370351050Z     await self.middleware_stack(scope, receive, send)
2024-11-24T09:03:54.370353501Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 735, in app
2024-11-24T09:03:54.370355963Z     await route.handle(scope, receive, send)
2024-11-24T09:03:54.370360365Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
2024-11-24T09:03:54.370362935Z     await self.app(scope, receive, send)
2024-11-24T09:03:54.370368796Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
2024-11-24T09:03:54.370371373Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-11-24T09:03:54.370373911Z   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-11-24T09:03:54.370376429Z     raise exc
2024-11-24T09:03:54.370378741Z   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-11-24T09:03:54.370381527Z     await app(scope, receive, sender)
2024-11-24T09:03:54.370384453Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
2024-11-24T09:03:54.370386939Z     response = await f(request)
2024-11-24T09:03:54.370389410Z   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 301, in app
2024-11-24T09:03:54.370391928Z     raw_response = await run_endpoint_function(
2024-11-24T09:03:54.370394329Z   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2024-11-24T09:03:54.370396884Z     return await dependant.call(**values)
2024-11-24T09:03:54.370399510Z   File "/app/apps/base/views.py", line 66, in share_file
2024-11-24T09:03:54.370402073Z     await file_storage.save_file(file, save_path)
2024-11-24T09:03:54.370404456Z   File "/app/core/storage.py", line 117, in save_file
2024-11-24T09:03:54.370406902Z     await s3.put_object(Bucket=self.bucket_name, Key=save_path, Body=await file.read(), ContentType=file.content_type)
2024-11-24T09:03:54.370409481Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/client.py", line 354, in _make_api_call
2024-11-24T09:03:54.370412013Z     http, parsed_response = await self._make_request(
2024-11-24T09:03:54.370414412Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/client.py", line 379, in _make_request
2024-11-24T09:03:54.370417242Z     return await self._endpoint.make_request(
2024-11-24T09:03:54.370420601Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 96, in _send_request
2024-11-24T09:03:54.370424255Z     request = await self.create_request(request_dict, operation_model)
2024-11-24T09:03:54.370427507Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 84, in create_request
2024-11-24T09:03:54.370431253Z     await self._event_emitter.emit(
2024-11-24T09:03:54.370434503Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/hooks.py", line 66, in _emit
2024-11-24T09:03:54.370438052Z     response = await resolve_awaitable(handler(**kwargs))
2024-11-24T09:03:54.370446916Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
2024-11-24T09:03:54.370453585Z     return await obj
2024-11-24T09:03:54.370457312Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/signers.py", line 24, in handler
2024-11-24T09:03:54.370464615Z     return await self.sign(operation_name, request)
2024-11-24T09:03:54.370467095Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/signers.py", line 80, in sign
2024-11-24T09:03:54.370469569Z     raise e
2024-11-24T09:03:54.370471953Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/signers.py", line 73, in sign
2024-11-24T09:03:54.370474433Z     auth = await self.get_auth_instance(**kwargs)
2024-11-24T09:03:54.370476807Z   File "/usr/local/lib/python3.9/site-packages/aiobotocore/signers.py", line 133, in get_auth_instance
2024-11-24T09:03:54.370479367Z     raise UnknownSignatureVersionError(
2024-11-24T09:03:54.370481936Z botocore.exceptions.UnknownSignatureVersionError: Unknown Signature Version: s3v2.
```

**Comment by vastsa** [comment]
应该是 sign 问题，等我加上这个设置

**Comment by vastsa** [comment]
晚点更新一下
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/c0851416-cdaa-407c-a084-febfd5b2f206">
