### ISSUE TITLE
新设备无法上传

### ISSUE THREAD

**Issue by wangjs-cool** [vastsa/FileCodeBox#23]
clone了最新版本，发现新设备访问时提示上传功能已关闭，当新设备登录admin后台一次后，再上传就成功了，已在两台设备上复现。

**Comment by vastsa** [comment]
是这样的哦，如果把ENABLE_UPLOAD设置为Flase，则仅允许管理员上传，就是需要登录admin才可以，不同设备不会同步登录状态

**Comment by wangjs-cool** [comment]
我记得我是配置了.env的，放在了data下，难道是配置错了，晚上我再确认一下。

**Comment by wangjs-cool** [comment]
我当时改过端口，.env肯定是生效了的，.env内容是从你的说明里copy的，ENABLE_UPLOAD默认是True我没改。

**Comment by vastsa** [comment]
ojbk，发现问题了，后端判断少了一个条件

**Comment by vastsa** [comment]
再试一下

**Comment by wangjs-cool** [comment]
好的  一会儿我试一下

**Comment by wangjs-cool** [comment]
上传可以成功，但是无法取件，快递柜取件报 Internal Server Error 。管理员后台取件报 {"detail":"Not Found"}。
![Snipaste_2022-12-27_21-10-24](https://user-images.githubusercontent.com/56024098/209671789-126e9de4-a2af-4910-94b2-41d3d4a04c54.png)
![Snipaste_2022-12-27_21-11-04](https://user-images.githubusercontent.com/56024098/209671802-937a10e0-1dac-4853-b0c2-0fe9d6749d37.png)

**Comment by wangjs-cool** [comment]
贴一下错误描述：
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/starlette/responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: 'data/static/upload/2022/12/27/1aee087f3d6b467593518170ffd0db48.apk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path data/static/upload/2022/12/27/1aee087f3d6b467593518170ffd0db48.apk does not exist.

**Comment by wangjs-cool** [comment]
data目录下确实未找到文件
```
root@localhost:~/code/FileCodeBox/data/static/upload/2022/12/27# ls -a
.  ..
```

**Comment by vastsa** [comment]
这个是设置的取件码过期方式为1次吗

**Comment by wangjs-cool** [comment]
设置的是1天

**Comment by vastsa** [comment]
好滴我看看哦

**Comment by wangjs-cool** [comment]
刚刚设置了3次也不行

**Comment by vastsa** [comment]
是间隔了多久呢

**Comment by wangjs-cool** [comment]
存完就取了  也就十几秒钟吧

**Comment by vastsa** [comment]
奇怪，我这边一直可以下载

**Comment by vastsa** [comment]
我把前两天新增的删除文件夹检查一下

**Comment by wangjs-cool** [comment]
我刚刚试了一下在windows上跑没问题，在linux里有问题，可能是权限问题，我检查一下

**Comment by vastsa** [comment]
我本地复现了，间隔时间长一点

**Comment by vastsa** [comment]
后台不能直接下载是正常的，但是前台的话我这边没有问题好像

**Comment by wangjs-cool** [comment]
我发现上传的时候报了错
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/responses.py", line 170, in __call__
    await self.background()
  File "/usr/local/lib/python3.7/dist-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/usr/local/lib/python3.7/dist-packages/starlette/background.py", line 26, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/root/code/FileCodeBox/storage.py", line 48, in save_file
    await asyncio.to_thread(self._save, filepath, file.file)
AttributeError: module 'asyncio' has no attribute 'to_thread'
```
是不是我linux少装了什么模块，python需要安什么模块你那边有汇总吗。我是看运行时报错少什么模块就安什么模块的。

**Comment by vastsa** [comment]
yes，python需要3.9以上

**Comment by wangjs-cool** [comment]
啊 我这是3.7啊

**Comment by wangjs-cool** [comment]
windows上是3.9，linux是3.7，看来真是版本问题

**Comment by vastsa** [comment]
3.9python才有这个特性

**Comment by wangjs-cool** [comment]
好的  我是用的debian10  安3.9还不太好安  我试一下

**Comment by wangjs-cool** [comment]
安装了3.9，问题已解决，非常感谢！

**Comment by vastsa** [comment]
客气啦，有问题欢迎随时反馈哦

**Comment by wangjs-cool** [comment]
可以加个好友吗，我又出现了一点问题……

**Comment by vastsa** [comment]
有问题可以提issue，这样后面的人也可以参考
