### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by losie** [vastsa/FileCodeBox#49]
Traceback (most recent call last):
  File "/www/wwwroot/FileCodeBox/main.py", line 34, in <module>
    app.mount('/static', StaticFiles(directory='./static'), name="static")
  File "/www/wwwroot/FileCodeBox/95a39f9d448586dff66fed8768eb2960_venv/lib/python3.7/site-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory './static' does not exist

**Comment by vastsa** [comment]
目测是中文版宝塔里面的Python项目管理，这个不知道怎么回事， 他将根目录设置在了系统根目录

**Comment by vastsa** [comment]
问题已解决，安装python项目管理器2.0即可
https://www.yuque.com/lxyo/work/lc1oe0xqk8t9b976?singleDoc# 《文件快递柜项目说明》
