### ISSUE TITLE
2.0新版本后台文件管理无法正常翻页

### ISSUE THREAD

**Issue by boyshu** [vastsa/FileCodeBox#90]
谢谢大佬的开源项目，该问题希望得到解决！具体报错如下：
Failed to load resource: the server responded with a status of 422 ()
index-fcb73ef2.js:1 Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at Xc (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:56942)
    at iu (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:58601)
    at te (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:38288)
    at V (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:37962)
    at P (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:37393)
    at Os.C [as fn] (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:41585)
    at Os.run (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:5430)
    at Q.a.update (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:41854)
    at Q (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:41880)
    at pe (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:40715)
index-fcb73ef2.js:1 DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at Xc (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:56942)
    at iu (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:58601)
    at te (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:38288)
    at V (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:37962)
    at P (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:37393)
    at Os.C [as fn] (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:41585)
    at Os.run (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:5430)
    at Q.a.update (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:41854)
    at ot (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:14169)
    at jo (https://pao.boyhu.cn/assets/index-fcb73ef2.js:1:15799)
kl @ index-fcb73ef2.js:1

**Comment by vastsa** [comment]
你好，我这边无法复现哦，翻页显示正常，可以将后台信息邮箱给我vast@tom.com
<img width="606" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/653846df-a408-43b3-81bf-5ece86314a42">

**Comment by boyshu** [comment]
![20230828201912](https://github.com/vastsa/FileCodeBox/assets/47899589/599d7866-2f5c-4213-aa13-a97e1b91d6ba)
![20230828201939](https://github.com/vastsa/FileCodeBox/assets/47899589/49200864-7b79-489a-82f8-650645944e4c)
![20230828202006](https://github.com/vastsa/FileCodeBox/assets/47899589/1f2cd57f-4f6f-4170-9ee1-42d3ab89a6f0)
![20230828202023](https://github.com/vastsa/FileCodeBox/assets/47899589/397eaf5c-0774-43ac-ba6b-2f1724aed49b)
谢谢回复，应该是代码里有错误字符，我是基于Docker安装的beta版本

**Comment by boyshu** [comment]
页码不对

**Comment by vastsa** [comment]
好的，似乎是page为小数导致的

**Comment by boyshu** [comment]
> 好的，似乎是page为小数导致的

谢谢，希望重新更新下Docker beta版本，有强迫症哈哈，目前重构版很棒，如果不涉及多用户或商用的话个人使用非常完美了。

**Comment by vastsa** [comment]
已修复
