### ISSUE TITLE
上传文件报错500

### ISSUE THREAD

**Issue by zhchy1996** [vastsa/FileCodeBox#96]
开发者你好

我在设置了文件上传大小后，上传文件报错500，错误信息如下
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/apps/base/views.py", line 41, in share_file
    if file.size > settings.uploadSize:
TypeError: '>' not supported between instances of 'int' and 'str'
```
查看 `config/update` 接口请求发现传回接口的值是 `string` 类型，而不是 `number` ，在更改类型后手动调用接口就没有问题了

看起来貌似是 `element-ui` 返回了错误的类型
https://github.com/vastsa/FileCodeBox/blob/67f09f9b817ac57d6f9f56c8f694354f94be7872/fcb-fronted/src/views/Admin/SettingView.vue#L19C23-L19C29

使用的版本是dokcer的beta版本

**Comment by vastsa** [comment]
收到，谢谢反馈

**Comment by vastsa** [comment]
已经修复了哦

**Comment by liuran001** [comment]
V2.1 似乎又出现了相同的问题，用的仍然是docker的beta版本
手动重新调用之后正常
日志和上面的一样就不贴了
